In [2]:
import numpy as np


In [3]:
list= [1,2,3,4]


In [6]:
array1=np.array(list) #creating ny array

In [8]:
type(array1) #type

numpy.ndarray

In [9]:
np.array([6,7,8,9])

array([6, 7, 8, 9])

In [10]:
array1.dtype

dtype('int64')

In [11]:
array2= np.array([1.2,2.3,4,5])
array2.dtype

dtype('float64')

In [12]:
array2.ndim #number of dimensions


1

In [23]:
array2.shape #dimension in tuple

(4,)

In [ ]:
#adding two lists in python isnt easy


In [27]:
matrix= np.array([[1,2,3],[4,5,6]])
(matrix)


array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
matrix.shape

(2, 3)

In [29]:
matrix.size

6

In [30]:
matrix.ndim

2

In [32]:
#Functions
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [37]:
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
np.linspace(0.1,1,10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [41]:
#Random No
np.random.rand(4,4)

array([[0.99503869, 0.05019687, 0.22037139, 0.97836105],
       [0.72485159, 0.10966097, 0.90340186, 0.19316304],
       [0.54556796, 0.85428743, 0.72206889, 0.83832424],
       [0.54763154, 0.4740029 , 0.41164831, 0.86824286]])

In [43]:
np.random.randint(1,100,5)

array([ 5, 94, 45, 37, 52])

In [ ]:
#Array Methods


In [52]:
np_array= np.arange(40)
print(np_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


In [50]:
np_array.shape

(10,)

In [51]:
np_array.size

10

In [53]:
np_array.reshape(4,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [58]:
np_ran_array = np.random.randint(1,101,10)
np_ran_array

array([26, 51, 36, 75, 34, 18, 54, 59, 30, 49])

In [62]:
print(np_ran_array.max())



75


In [63]:
print(np_ran_array.min())

18


In [64]:
print(np_ran_array.argmin())

5


In [66]:
array= np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
array[5]

np.int64(5)

In [69]:
array[3:6]

array([3, 4, 5])

In [70]:
array[3:6]=10
array

array([ 0,  1,  2, 10, 10, 10,  6,  7,  8,  9])

In [74]:
array2= np.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
array2_slice= array2[2:7]
array2_slice

array([2, 3, 4, 5, 6])

In [76]:
array2_slice[2:3]=100
array2_slice

array([  2,   3, 100,   5,   6])

In [77]:
array_2d= np.array([[10,20,30],[40,50,60],[70,80,90]])
array_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [79]:
array_2d[0]

array([10, 20, 30])

In [80]:
array_2d[0][1]

np.int64(20)

In [81]:
array_2d[2][0]

np.int64(70)

In [83]:
slice_2d= slice.array_2d[0:2,1:3]

AttributeError: type object 'slice' has no attribute 'array_2d'

In [85]:
numbers= np.arange(0,11)
numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [86]:
numbers <6

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])